name: magnetro
description: "A new Flutter project."
publish_to: 'none'
version: 9842.2224.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  cookie_jar: ^4.0.9
  dio_cookie_manager: ^3.4.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^8.1.0
  flutter_neumorphic_plus: ^3.5.0
  get: ^4.7.3
  url_launcher: ^6.3.0
  media_kit: ^1.2.6                  # Core player
  media_kit_video: ^2.0.1            # Video rendering widget
  media_kit_libs_video: ^1.0.7 
  window_manager: ^0.5.1      # Native libs (includes audio support too)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  fonts:
    - family: UberMove
      fonts:
        - asset: assets/fonts/UberMove-Regular.otf
          weight: 400
        - asset: assets/fonts/UberMove-Medium.otf
          weight: 500
        - asset: assets/fonts/UberMove-Bold.otf
          weight: 700